### ISSUE TITLE
Loading limit

### ISSUE THREAD

**Issue by JuanGildeGP** [square/square-python-sdk#110]
Hello, while loading the payments it is only loading 100 data entries. When I transform into a DF I only get 100 rows. I know I have more data entries than 100. Is there some limitation while loading with SquareUp's API? If so, how can I change this limit. 

Thanks a lot in advance!

**Comment by zenmasterjobo** [comment]
Hi @JuanGildeGP 

@stevealdred is correct. I hope this helps.

Also just wanted to plug and FYI that your questions are better asked over at our [Developer Forums](https://developer.squareup.com/forums) - these forums are monitored by Square Employees, and has an active community!

cheers!
