### ISSUE TITLE
Receiving INTERNAL_SERVER_ERROR error message when OAuth token expires

### ISSUE THREAD

**Issue by jasonwalsh** [square/square-python-sdk#20]
Per the [documentation](https://developer.squareup.com/docs/oauth-api/cookbook/renew-oauth-tokens):

> OAuth tokens need to be renewed regularly because they expire after 30 days.

When I invoke the [`batch_retrieve_catalog_objects`](https://github.com/square/square-python-sdk/blob/462a24965123d1f8f0af76aab721f177b2a88e64/square/api/catalog_api.py#L76) method of the catalog API, I receive the following error message:

```json
{
  "errors": [
    {
      "category": "API_ERROR",
      "code": "INTERNAL_SERVER_ERROR",
      "detail": "We were unable to authorize this request due to an internal error."
    }
  ]
}
```

I reauthorized the application to generate a new OAuth token and the method invocation succeeded.

It seems that `INTERNAL_SERVER_ERROR` is the incorrect code to return if the token expires, considering there is a [`ACCESS_TOKEN_EXPIRED`](https://github.com/square/square-python-sdk/blob/master/doc/models/error-code.md) error code.

Any ideas on what could be causing the issue?

FWIW, I received this error message at `2020-01-10 12:28:03.381` EST.

Please let me know if any additional information is required or if I should contact support.

**Comment by StephenJosey** [comment]
Hi @jasonwalsh thanks for reporting. This is unfortunately a known issue with the Catalog API. Any invalid access tokens (including expired tokens) will result in a 500 Internal server error. The Catalog team is working on resolving this, but for now I'll eave this ticket open until I have more info.

**Comment by jasonwalsh** [comment]
Thanks for the prompt response @StephenJosey!

**Comment by StephenJosey** [comment]
This issue has officially been resolved in Catalog's API. Closing this out, thanks!
