### ISSUE TITLE
Links to models in are broken in the docs

### ISSUE THREAD

**Issue by JamesVorder** [square/square-python-sdk#21]
When using the generated docs here on Github, the links to all the models are broken.

For example, the link to "Create Order Request" on [Create Orders](https://github.com/square/square-python-sdk/blob/master/doc/orders.md#create-order) points to `https://github.com/square/square-python-sdk/blob/master/doc/$m/CreateOrderRequest`, when it should point to `https://github.com/square/square-python-sdk/blob/master/doc/models/create-order-request.md`.

This affects my ability to successfully use the documentation as I build software that consumes the API. It's not necessarily unusable (I can manually search through the `models` folder, but it would certainly be nice if these links were fixed.

Thank you in advance for any help on this issue!

**Comment by sseaman** [comment]
Thanks for pointing this out.  We are aware of this issue and working on a solution.

**Comment by sseaman** [comment]
This has been fixed in the most recent release.  If you find this anywhere else, please tell us!
