### ISSUE TITLE
Example Paging?

### ISSUE THREAD

**Issue by micahasmith** [square/square-python-sdk#26]
Looking for examples on 

1. where to look in results to tell if we need to page
2. how to do the paging requests

for listing locations/orders/transactions

**Comment by timtoyoshima** [comment]
You need to read the cursor value in the response. Search for "Check the cursor for list operations" in the readme and there is an example there of looping through all the pages. Let me know if that helps.

**Comment by micahasmith** [comment]
BAM ty!
