### ISSUE TITLE
Upgrading the jsonpickle dependency 

### ISSUE THREAD

**Issue by SnijderC** [square/square-python-sdk#56]
The jsonpickle version you are using is a bit outdated, wonder if you could update it to a more recent version. 
In your setup.py file versions allowed are `>=0.7.1, <1.0`, those versions are from 2018.

You `requirements.txt` says: `~=1.4, >= 1.4.1`, those versions are about a year old.

When we install the sdk from pypi, the `setup.py` version is leading, so the jsonpickle version is `<1.0`. Is that intentional? Especially given your `requirements.txt` has a version 2 years younger..

When combined with other dependencies this leads to dependency clashes.

**Comment by psi29a** [comment]
@joanc-sq @mohsin-sq Can we get some visibility here? This is starting to have an impact downstream:

```
  venv/lib/python3.8/site-packages/jsonpickle/pickler.py:253: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
    return {tags.B64: base64.encodestring(obj).decode('utf-8')}
```

Can you please advise here?

**Comment by wolfadex** [comment]
`jsonpickle` has been updated in #75 and version 14.1.1.20210915 has published to [pypi](https://pypi.org/project/squareup/).

Thank you for bringing this to our attention and happy coding!

**Comment by psi29a** [comment]
Thank you @wolfadex ! :)
