### ISSUE TITLE
Cards Disable Card Endpoint

### ISSUE THREAD

**Issue by kartikye** [square/square-python-sdk#61]
The following error occurs when trying to disable a card

```
<ApiResponse [{"errors":[{"category":"INVALID_REQUEST_ERROR","code":"EXPECTED_JSON_BODY","detail":"Expected body to be a JSON object."}]}]>
```

**Comment by zenmasterjobo** [comment]
Hi @kartikye

I have confirmed that on our latest SDK version, disabling a card succeeds.

If you continue to have issues with this in the future. Please consider making a post on our [Developer Forums](https://developer.squareup.com/forums) as this forum is monitored by Square Employees and has regular engagement.

Cheers!
