### ISSUE TITLE
how to get all order?

### ISSUE THREAD

**Issue by m986883511** [square/square-python-sdk#87]

**Comment by wolfadex** [comment]
I believe the [Orders Search](https://developer.squareup.com/reference/square/orders-api/search-orders) endpoint is what you're looking for. With the SDK the corresponding [docs are here](https://github.com/square/square-python-sdk/blob/master/doc/api/orders.md#search-orders).

For any future questions regarding how to use APIs, please also checkout our [API docs](https://developer.squareup.com/reference/square), our [forums](https://developer.squareup.com/forums/), and our [developer Slack](https://buildwithsquare.slack.com/ssb/redirect).
